version: '3'
services:
   mongo:
      image: "mongo:4.4.7"
      container_name: "soilemongo"
      ports:
         - "27017:27017"
      volumes:
         - /root/soiledb:/data/db
   soile:
      build: .
      ports:
         - "8080:8080"
      volumes:
         - ./http_server/main/resources/static_files:/soile/http_server/main/resources/static_files
         - ./http_server/main/resources/templates:/soile/http_server/main/resources/templates
         - /root/soilevideos:/soile/mods/fi.abo.kogni.soile~http-server~1.0/static_files/exp_video_upload
